#!/bin/bash

# Update Grub
update-grub > /dev/null 2>&1

# Update mimetype datebase
update-mime-database /usr/share/mime > /dev/null 2>&1

set -e

# Disable Wayland
sed -is "s/^#WaylandEnable=false/WaylandEnable=false/" /etc/gdm3/daemon.conf

set -u
ckbi=/usr/lib/firefox-esr/libnssckbi.so
if [ -z "$(dpkg-divert --listpackage $ckbi)" ]; then
    dpkg-divert --package scibian-desktop \
            --rename --divert $ckbi.firefox-esr \
            --add $ckbi
    ln -sf ../x86_64-linux-gnu/pkcs11/p11-kit-trust.so $ckbi
fi
unset ckbi
set +u

set -u
ckbi=/usr/lib/iceweasel/libnssckbi.so
if [ scibian-desktop = "$(dpkg-divert --listpackage $ckbi)" ]; then
    unlink $ckbi
    dpkg-divert --package scibian-desktop \
            --rename --remove $ckbi
fi
unset ckbi
set +u

trackerservices=("tracker-extract.service" "tracker-miner-apps.service" "tracker-miner-fs.service" "tracker-store.service" "tracker-writeback.service")

for ts in "${trackerservices[@]}"; do
  fullpath="/etc/systemd/user/"${1}
  if [ ! -L ${fullpath} ] && [ $(readlink -f ${fullpath}) = "/dev/null" ]; then
    echo "not masking"
  else
    systemctl --user --global mask $ts
  fi
done

#DEBHELPER#

update-alternatives --install \
  /usr/share/images/vendor-logos \
  vendor-logos \
  /usr/share/icons/scibian 100 \
  --slave /usr/share/icons/vendor/64x64/emblems/emblem-vendor.png \
  emblem-vendor-64 \
  /usr/share/icons/scibian/png/scibian_small_64.png \
  --slave /usr/share/icons/vendor/128x128/emblems/emblem-vendor.png \
  emblem-vendor-128 \
  /usr/share/icons/scibian/png/scibian_small_128.png \
  --slave /usr/share/icons/vendor/256x256/emblems/emblem-vendor.png \
  emblem-vendor-256 \
  /usr/share/icons/scibian/png/scibian_small_256.png \
  --slave /usr/share/icons/vendor/scalable/emblems/emblem-vendor.svg \
  emblem-vendor-scalable \
  /usr/share/icons/scibian/scalable/scibian_small.svg \
  --slave /usr/share/icons/vendor/64x64/emblems/emblem-vendor-symbolic.png \
  emblem-vendor-symbolic-64 \
  /usr/share/icons/scibian/png/scibian_small_symbolic_64.png \
  --slave /usr/share/icons/vendor/128x128/emblems/emblem-vendor-symbolic.png \
  emblem-vendor-symbolic-128 \
  /usr/share/icons/scibian/png/scibian_small_symbolic_128.png \
  --slave /usr/share/icons/vendor/256x256/emblems/emblem-vendor-symbolic.png \
  emblem-vendor-symbolic-256 \
  /usr/share/icons/scibian/png/scibian_small_symbolic_256.png \
  --slave /usr/share/icons/vendor/scalable/emblems/emblem-vendor-symbolic.svg \
  emblem-vendor-symbolic-scalable \
  /usr/share/icons/scibian/scalable/scibian_small_symbolic.svg \
  --slave /usr/share/icons/vendor/64x64/emblems/emblem-vendor-white.png \
  emblem-vendor-white-64 \
  /usr/share/icons/scibian/png/scibian_small_white_64.png \
  --slave /usr/share/icons/vendor/128x128/emblems/emblem-vendor-white.png \
  emblem-vendor-white-128 \
  /usr/share/icons/scibian/png/scibian_small_white_128.png \
  --slave /usr/share/icons/vendor/256x256/emblems/emblem-vendor-white.png \
  emblem-vendor-white-256 \
  /usr/share/icons/scibian/png/scibian_small_white_256.png \
  --slave /usr/share/icons/vendor/scalable/emblems/emblem-vendor-white.svg \
  emblem-vendor-white-scalable \
  /usr/share/icons/scibian/scalable/scibian_small_white.svg

exit 0
