#!/bin/sh

set -e

# Use Bash as default shell for new users

echo "SHELL=/bin/bash" > /etc/default/useradd

# Generic group Creation
# scibian-users chroot group creation and adding to pam_group
addgroup --system --quiet chroot
addgroup --system --quiet scibian-users


# PAM update
pam-auth-update --package

# Création du dossier de journalisation
if [ ! -d /var/log/journal ]; then
  mkdir /var/log/journal
fi

if [ ! -d /var/lib/scibian ]; then
  mkdir /var/lib/scibian/
fi



#DEBHELPER#
